# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0002_auto_20170610_0210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ext', to=settings.AUTH_USER_MODEL),
        ),
    ]
