# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 22:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0003_auto_20170611_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='value',
            field=models.FloatField(default=0),
        ),
    ]
