# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-10 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mycollections', '0004_auto_20170611_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extended',
            name='value',
            field=models.CharField(default='0', max_length=150),
        ),
    ]
